name: build-status-check

on:
  pull_request:
    types: [edited, synchronize]
    branches:
      - master

jobs:
  Check_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build React App
        run: npm install && npm run build
