name: increment-version

on:
  pull_request:
    types: [synchronize, edited]
    branches:
      - master

jobs:
  Increment_Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{steps.extract_branch.outputs.branch}}

      - name: Build React App
        run: npm install && npm run build
