name: increment-version

on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  Increment_Version:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{steps.extract_branch.outputs.branch}}

      - name: Get Version Number
        id: getVersionNumber
        run: |
          content=`cat package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"

      - if: startsWith(steps.extract_branch.outputs.branch, 'feature/')
        name: Increment Minor Version Number
        id: incrementMinorVersion
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "feature"

      - if: startsWith(steps.extract_branch.outputs.branch, 'feature/')
        name: Update Version Number Variable
        run: |
          echo "version=${{steps.incrementMinorVersion.outputs.next-version}}" >> $GITHUB_ENV

      - name: Increment Patch Version Number
        id: incrementPatchVersion
        if: startsWith(steps.extract_branch.outputs.branch, 'bug/')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "bug"

      - if: startsWith(steps.extract_branch.outputs.branch, 'bug/')
        name: Update Version Number Variable
        run: |
          echo "version=${{steps.incrementPatchVersion.outputs.next-version}}" >> $GITHUB_ENV

      - name: Increment Major Version Number
        id: incrementMajorVersion
        if: startsWith(steps.extract_branch.outputs.branch, 'overhaul/')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "major"

      - if: startsWith(steps.extract_branch.outputs.branch, 'overhaul/')
        name: Update Version Number Variable
        run: |
          echo "version=${{steps.incrementMajorVersion.outputs.next-version}}" >> $GITHUB_ENV

      - name: Update Version Number
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: version
          value: ${{ env.version }}

      - name: Commit New Version
        uses: EndBug/add-and-commit@v9
        with:
          message: Commit from GitHub Actions - updated version number to ${{ env.version }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
