name: s3-depl

on:
  push:
    branches:
      - pipeline-test

jobs:
  Build_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - id: getVersionNumber
        run: |
          content=`cat package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"

      - run: |
          echo "${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}"

      - if: startsWith(${{ steps.extract_branch.outputs.branch }}, 'pipeline-test')
        name: Increment Minor Version Number
        id: incrementMinorVersion
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "feature"

      - if: startsWith(${{ steps.extract_branch.outputs.branch }}, 'pipeline-test')
        run: |
          echo "version=$steps.incrementMinorVersion.outputs.next-version" >> $GITHUB_ENV

      - if: startsWith(${{ steps.extract_branch.outputs.branch }}, 'bug/')
        name: Increment Patch Version Number
        id: incrementPatchVersion
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "bug"

      - if: startsWith(${{ steps.extract_branch.outputs.branch }}, 'bug/')
        run: |
          echo "version=$steps.incrementPatchVersion.outputs.next-version" >> $GITHUB_ENV

      - run: echo "$VERSION"

      - name: Update Version Number
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: version
          value: ${{ env.version }}

      - name: Commit New Version
        uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com

      # - name: Build React App
      #   run: npm install && npm run build

      # - name: Deploy app build to S3 bucket
      #   run: aws s3 sync ./build/ s3://joshkotrous.io --delete

      # - name: Invalidate CloudFront
      #   uses: chetan/invalidate-cloudfront-action@v2
      #   env:
      #     DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      #     PATHS: "/*"
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
