name: versioning

on:
  pull_request:
    types: [opened]
    branches:
      - test-versioning

jobs:
  Build_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Extract branch name
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: |
          echo ${{steps.extract_branch.outputs.branch}}

      - run: |
          echo ${GITHUB_BASE_REF}

      - id: getVersionNumber
        run: |
          content=`cat package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"

      - if: startsWith(steps.extract_branch.outputs.branch, 'feature/')
        name: Increment Minor Version Number
        id: incrementMinorVersion
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "feature"

      - if: startsWith(steps.extract_branch.outputs.branch, 'feature/')
        name: Update Version Number Variable
        run: |
          echo "version=${{steps.incrementMinorVersion.outputs.next-version}}" >> $GITHUB_ENV

      - name: Increment Patch Version Number
        id: incrementPatchVersion
        if: startsWith(steps.extract_branch.outputs.branch, 'bug/')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "bug"

      - if: startsWith(steps.extract_branch.outputs.branch, 'bug/')
        name: Update Version Number Variable
        run: |
          echo "version=${{steps.incrementPatchVersion.outputs.next-version}}" >> $GITHUB_ENV

      - name: Increment Major Version Number
        id: incrementMajorVersion
        if: startsWith(steps.extract_branch.outputs.branch, 'overhaul/')
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{fromJson(steps.getVersionNumber.outputs.packageJson).version}}
          version-fragment: "major"

      - if: startsWith(steps.extract_branch.outputs.branch, 'overhaul/')
        name: Update Version Number Variable
        run: |
          echo "version=${{steps.incrementMajorVersion.outputs.next-version}}" >> $GITHUB_ENV

      - name: Update Version Number
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: version
          value: ${{ env.version }}

      - name: Commit New Version
        uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
